### ISSUE TITLE
[FT-001] Frameの実装

### ISSUE THREAD

**Issue by takapi327** [takapi327/flutter-tutorials#2]
# Frameの実装
## [Frame](https://flame-engine.org/)
[Github flame-engine/flame](https://github.com/flame-engine/flame)
設定
バージョンは、[こちら](https://pub.dev/packages/frame)とGithubの[tags](https://github.com/flame-engine/flame/tags)を参照
```yml
dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0-rc6 <- 追加
```
読み込み
```Shell
$ flutter pub get
```
## シュートリアル
[Create a Mobile Game with Flutter and Flame – Beginner Tutorial](https://jap.alekhin.io/create-mobile-game-flutter-flame-beginner-tutorial)
## 参考文献
[[Flutter用ゲームエンジン] Flutter & Flame 試してみた](https://qiita.com/LAGALIN/items/65e9a6ca5ffcb2f34073)
